name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run type checks
        run: npx tsc -p tsconfig.json --noEmit
      - name: Build frontend
        run: npm run build
      - name: Lint
        run: npm run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Unit & Component Tests
        run: npm run test:unit

      # Start the frontend server in the background
      - name: Start frontend server
        run: |
          nohup npm run preview -- --port 5173 &
        shell: bash

      # Wait for the server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
